//
//  ClassifierManager.swift
//  AIProxyBootstrap
//
//  Created by Lou Zell
//

import SwiftUI

@MainActor
@Observable
final class ClassifierManager {
    /// The description of a plant. Descriptions are generated by OpenAI
    private(set) var plantDescription: String?

    /// The image of a plant. This camera image is supplied by the user
    private(set) var image: CGImage?

    /// A wikipedia URL for the user to learn more about the identified plant. This URL is generated by OpenAI
    private(set) var wikipediaURL: URL?

    /// Loads data from OpenAI
    private let classifierDataLoader = ClassifierDataLoader()

    /// Identify a plant based on a passed in image
    /// - Parameter image: a camera frame that the user took of a plant in their surroundings
    func identify(_ image: CGImage) {
        self.image = image
        Task {
            let (description, wikipediaURL) = try await classifierDataLoader.identify(fromImage: image)
            self.plantDescription = description
            self.wikipediaURL = wikipediaURL
        }
    }
    
    /// Reset all previously classified state
    func reset() {
        self.plantDescription = nil
        self.image = nil
        self.wikipediaURL = nil
    }
}
